number1=input('Enter number1:')
number2=input('Enter number 2:')
number3= input('Enter number3:')
number4=input('Enter number 4:')
number5=input('Enter number 5:')

print(type(number1))

sum=int(number1)+int(number2)+int(number3)+int(number4)+int(number5)
print(sum)
product=int(number1)*int(number2)*int(number3)*int(number4)*int(number5)
print(product)
difference=int(number1)-int(number2)-int(number3)-int(number4)-int(number5)
print(difference)
Divide_a=int(number1)/int(number2)
print(Divide_a)
Divide_b=int(number3)/int(number4)
print(Divide_b)
Divide_c=int(number4)/int(number5)
print(Divide_c)